spring:
  datasource:
    url: jdbc:mysql://39.107.93.44:3306/gy-peak?useUnicode=true&characterEncoding=UTF-8
    username: gy-peak
    password: gy-peak.1
    driver-class-name: com.mysql.cj.jdbc.Driver